name: web3app

services:
  # Enable when you need tenant isolation and rate limiting
  # postgres:
  #   image: postgres:16.4-alpine
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: "123456"
  #     POSTGRES_DB: web3_rpc_proxy_db
  #   networks: [app-bridge]
  #   ports: [5432:5432]

  # Enable when you need tenant isolation and rate limiting
  # redis:
  #   image: redis:7.4.0-alpine
  #   ports: [6379:6379]
  #   networks: [app-bridge]

  # Provides the free web3 rpc
  # provider:
  #   image: dodozoo/we3-rpc-provider:v1.0.0
  #   networks: [app-bridge]
  #   ports: [3000:3000]

  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/app/logs
      - ./config/default.yaml:/app/config/default.yaml:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - LOG_LEVEL=debug
      - LOG_PRETTIER=true
      - LOG_TIME_FORMAT="2006-01-02 15:04:05.000"
    user: "1000:1000"
    # depends_on:
    #   - provider
      # - postgres
      # - redis
    # links:
    #   - provider
      # - postgres
      # - redis
    networks: [app-bridge]
    ports: [8080:8080]

networks:
  app-bridge:
    driver: bridge
