# default.yaml is the default configuration file
# For local development, you can create a local.yaml to override the default configuration

# Service configuration
app:
  # Service name
  name: "Web3 RPC Proxy"
  # Host and port where the service listens
  host: :8080
  # Expiration time for keep-alive connections
  idle-timeout: 30s
  # Print registered routes
  print-routes: false
  # Whether to enable prefork
  prefork: false
  # Enable production mode
  production: false

# Logger configuration
logger:
  level: debug
  prettier: true
  time-format: "2006-01-02 15:04:05.000"
  file:
    enabled: true
    path: "/app/logs/app.log"
    max-size: 100  # MB
    max-backups: 3
    max-age: 7     # days
    compress: true
  websocket:
    enabled: true
    path: "/app/logs/websocket.log"
    max-size: 100  # MB
    max-backups: 3
    max-age: 7     # days
    compress: true

# Database configuration
# database:
#   postgres:
#     dsn: 'postgres://your-postgres-host:5432/your_db_name'

# Redis configuration for data caching
redis:
  url: 'redis://redis:6379'
  keeplive-interval: 5s
  retry-count: 3

# AMQP configuration, after startup, the service will automatically create an exchange
# based on the following configuration and send request information to this exchange
# amqp:
#   url: amqp://your-mq-host:5672
#   exchange: "your-exchange-name" # default: "web3rpcproxy.query.topic"
#   exchange-type: "topic"

# Tenant configuration
# tenant:
#   enable: true # Enable tenants rate limit

# Data caching
cache:
  results:
    disable: false
    ttl: 15m
    expiry_durations:
      net_version:
        ttl: 99h
      eth_chainId:
        ttl: 99h
      # eth_getTransactionCount:
      #   ttl: 24h
      eth_getBlockTransactionCountByNumber:
        ttl: 24h
      eth_getBlockTransactionCountByHash:
        ttl: 24h
      eth_getUncleCountByBlockHash:
        ttl: 24h
      eth_getUncleCountByBlockNumber:
        ttl: 24h
      eth_blockNumber:
        ttl: 24h
      eth_getBlockByNumber:
        ttl: 24h
      eth_getBlockByHash:
        ttl: 24h
      eth_getTransactionByHash:
        ttl: 24h
      eth_getTransactionByBlockHashAndIndex:
        ttl: 24h
      eth_getTransactionByBlockNumberAndIndex:
        ttl: 24h
      eth_getTransactionReceipt:
        ttl: 24h
      # eth_getLogs:
      #   ttl: 10m
      eth_getUncleByBlockHashAndIndex:
        ttl: 24h
      eth_getUncleByBlockNumberAndIndex:
        ttl: 24h

# Provider configuration, it will auto load external endpoints
# providers:
#   web3-rpc-provider:
#     url: "http://your_host:3000/endpoints"
#     sources:
#     - ChainList

# Endpoint configuration, provides endpoint lists for each chain for the system to choose from
endpoints:
  # Chain ID
  - id: 8453
    # Chain code
    code: base
    # Different types of endpoints
    services:
      activenode:
        list:
          - url: "wss://base-rpc.publicnode.com"
          - url: "https://base.drpc.org"
          - url: "https://mainnet.base.org"

providers:
  web3-rpc-provider:
    disable: true